apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-api
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        kubernetes.io/ingress.class: nginx
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        role: fn-service
    spec:
      {{- if .Values.fnserver.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fnserver.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fnserver.tolerations }}
      tolerations:
{{ toYaml .Values.fnserver.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: fn-service
        image: {{ .Values.fnserver.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.fnserver.resources | indent 12 }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /v1/apps
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: LOG_LEVEL
          value: {{ .Values.fnserver.logLevel }}
        - name: FN_PORT
          value: "80"
        - name: FN_DB_USER
          value: {{ .Values.fnserver.fndbUser }}
        - name: FN_DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fnserver.fndb }}
              key: mysql-password
        - name: FN_DB_HOST
          value: {{ .Values.fnserver.fndb }}
        - name: FN_DB_URL
          value: mysql://$(FN_DB_USER):$(FN_DB_PASSWD)@tcp($(FN_DB_HOST):3306)/fndb
        - name: FN_MQ_HOST
          value: {{ .Values.fnserver.fnmq }}
#  TODO:
#        - name: MQ_PASSWD
#          valueFrom:
#            secretKeyRef:
#              name: {{ .Release.Name }}-redis
#              key: redis-password
        - name: FN_MQ_URL
          value: redis://$(FN_MQ_HOST):6379/
        - name: FN_JAEGER_HOST
          value: {{ .Values.fnserver.fnjaeger }}          
        - name: FN_JAEGER_URL
          value: http://$(FN_JAEGER_HOST):14268